### ISSUE TITLE
Maps inconnues

### ISSUE THREAD

**Issue by ISSOtm** [PramaInitiative/Phoebe#3]
Certaines des maps du [Google Doc](https://docs.google.com/spreadsheets/d/1RpBER6uUUCJbRpG74n-hb2ehnNCcEp07VW-hRk-8YD0/edit?pli=1#gid=799260435) sont marquées comme "Ville - Bâtiment ou Maison". Il faut préciser desquelles il s'agit.

La liste de Phoebe actuelle (commit bef584194cde8d28a8a71f9e0a447299819865cb) a partiellement complété cette feuille Google Docs, mais ce n'est pas assez (les "??? (Ville)" sont toujours inconnus).

J'assigne BUGLITCH, il s'y connaît bien.

**Comment by ISSOtm** [comment]
La liste a été mise à jour (commits 779da2ec0b8b205bab20a6368bdc768aceedf314, 38f3d349465cd4bd84e75c1ea09fd611b6c0bb5c et 1aabfa2df3cc91df523d8c9e3dcec383f50fb388) mais est largement incomplète (surtout après la map 206).

**Comment by Ankeraout** [comment]
La liste a été mise à jour et complétée dans le commit e757ae5.
