### ISSUE TITLE
Liste des localisations

### ISSUE THREAD

**Issue by Ankeraout** [PramaInitiative/Phoebe#7]
Quand on clique sur une ville, la liste des localisations se réduit en effet aux localisations de cette ville.
Par contre, quand on clique sur un endroit non supporté, la liste ne se remet pas à jour.

Exemple : clic sur féli-cité, puis sur unionpolis.

**Comment by ISSOtm** [comment]
Je m'en occuperai avec Benji, donc je n'assigne aucun de nous deux :)

**Comment by Ankeraout** [comment]
Bug corrigé dans le commit b2aab0a.

**Comment by ISSOtm** [comment]
Bon, au final il l'a fait tout seul. Trop fort.
